import { Parent } from "../models/parent.model" 

  export const  parents: Parent[] = [
    {
        id:1,
        firstName: 'Koen',  
        lastName: 'Van den Eynde',
        phoneNumber: '0475123456',
        email: ' ',           
        sortOrder: 1,
        studentId: 1,
        addressSameAsStudent: true,
        occupation: 'Engineer',
        workPhoneNumber: '0123456789',
        workEmail: '     ',
        isPrimaryContact: true,     
        receivesInvoices: true,
        receivesReports: true,
        receivesMailings: false,        
        receivesSms : true,
        relationshipToStudent: 'Father',
        comments: 'No comments',
        createdAt: new Date(),
        updatedAt: new Date(),  
        createdBy: 'admin',
        updatedBy: 'admin',
        isActive: true, 
        isDeleted: false
    },
    {
        id:2,
        firstName: 'Maria',  
        lastName: 'Janssens',
        phoneNumber: '0486123456',
        email: '            ',
        sortOrder: 2,
        studentId: 1,
        relationshipToStudent: 'Mother',
        addressSameAsStudent: true,
        occupation: 'Teacher',
        workPhoneNumber: '0987654321',
        workEmail: '   ',
        isPrimaryContact: false,
        receivesInvoices: false,
        receivesReports: true,
        receivesMailings: true,
        receivesSms : true,
        comments: 'No comments',
        createdAt: new Date(),
        updatedAt: new Date(),  
        createdBy: 'admin', 
        updatedBy: 'admin',
        isActive: true, 
        isDeleted: false    
    }
]