import { Parent } from "../models/parent.model" 

  export const  parents: Parent[] = [
    {
        id:1,
        firstName: 'Jan',  
        lastName: 'Van den Eynde',
        phoneNumber: '0475123456',
        email: 'Koen.Van den Eynde@test.com',           
        sortOrder: 1,
        studentId: 1,
        addressSameAsStudent: true,
        occupation: 'Engineer',
        workPhoneNumber: '0123456789',
        workEmail: '     ',
        isPrimaryContact: true,     
        receivesInvoices: true,
        receivesReports: true,
        receivesMailings: false,        
        receivesSms : true,
        relationshipToStudent: 1,
        comments: 'No comments',
        createdAt: new Date(),
        updatedAt: new Date(),  
        createdBy: 'admin',
        updatedBy: 'admin',
        isActive: true, 
        isDeleted: false
    },
    {
        id:2,
        firstName: 'Maria',  
        lastName: 'Janssens',
        phoneNumber: '0486123456',
        email: 'Maria.Janssens@test.be',
        sortOrder: 2,
        studentId: 1,
        relationshipToStudent: 2,
        addressSameAsStudent: true,
        occupation: 'Teacher',
        workPhoneNumber: '0987654321',
        workEmail: '   ',
        isPrimaryContact: false,
        receivesInvoices: false,
        receivesReports: true,
        receivesMailings: true,
        receivesSms : true,
        comments: 'No comments',
        createdAt: new Date(),
        updatedAt: new Date(),  
        createdBy: 'admin', 
        updatedBy: 'admin',
        isActive: true, 
        isDeleted: false    
    },
    {
        id:3,
        firstName: 'Liesbeth',  
        lastName: 'Peeters',
        phoneNumber: '0497123456',
        email: '    ',
        sortOrder: 3,
        studentId: 1,
        relationshipToStudent: 4,
        addressSameAsStudent: false,
        occupation: 'Nurse',        
        workPhoneNumber: '0112233445',
        workEmail: '   ',
        isPrimaryContact: false,
        receivesInvoices: false,
        receivesReports: false,
        receivesMailings: true,
        receivesSms : false,
        comments: 'No comments',
        createdAt: new Date(),
        updatedAt: new Date(),  
        createdBy: 'admin', 
        updatedBy: 'admin',
        isActive: true, 
        isDeleted: false    
    }
]